name: Terraform Destroy
on: workflow_dispatch
env:
  AWS_ACCRESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECREY_ACCESS_ID: ${{secrets.AWS_SECREY_ACCESS_ID}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
